# New MongoDB Atlas connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=Stock_Market

alpha.vantage.api.key=37HX22V1HWPIIEMG
server.port=8080

spring.cache.cache-names=dashboardData,marketData,stockPrices
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15m

alpha.vantage.rate.limit=5

# Groq AI Config (Faster & Free)
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
